Updated files names in deploy dir

diff --git a/deploy/2-kafka-zookeeper.yaml b/deploy/2-kafka-zookeeper.yaml
--- a/deploy/2-kafka-zookeeper.yaml
+++ b/deploy/2-kafka-zookeeper.yaml
@@ -1,67 +1,66 @@
 apiVersion: v1
-items:
-- apiVersion: v1
-  data:
-    setup.sh: |-
-      #!/bin/bash
+data:
+  setup.sh: |-
+    #!/bin/bash
 
-      ID="${MY_POD_NAME#"kafka-local-"}"
-      if [[ -f "/bitnami/kafka/data/meta.properties" ]]; then
-          export KAFKA_CFG_BROKER_ID="$(grep "broker.id" "/bitnami/kafka/data/meta.properties" | awk -F '=' '{print $2}')"
-      else
-          export KAFKA_CFG_BROKER_ID="$((ID + 0))"
-      fi
+    ID="${MY_POD_NAME#"kafka-local-"}"
+    if [[ -f "/bitnami/kafka/data/meta.properties" ]]; then
+        export KAFKA_CFG_BROKER_ID="$(grep "broker.id" "/bitnami/kafka/data/meta.properties" | awk -F '=' '{print $2}')"
+    else
+        export KAFKA_CFG_BROKER_ID="$((ID + 0))"
+    fi
 
-      # Configure zookeeper client
+    # Configure zookeeper client
 
-      exec /entrypoint.sh /run.sh
-  kind: ConfigMap
-  metadata:
-    annotations:
-      meta.helm.sh/release-name: kafka-local
-      meta.helm.sh/release-namespace: kafkaplaypen
-    labels:
-      app.kubernetes.io/instance: kafka-local
-      app.kubernetes.io/managed-by: Helm
-      app.kubernetes.io/name: kafka
-      helm.sh/chart: kafka-20.0.0
-    name: kafka-local-scripts
-    namespace: kafkaplaypen
-- apiVersion: v1
-  data:
-    init-certs.sh: '#!/bin/bash'
-    setup.sh: |-
-      #!/bin/bash
+    exec /entrypoint.sh /run.sh
+kind: ConfigMap
+metadata:
+  annotations:
+    meta.helm.sh/release-name: kafka-local
+    meta.helm.sh/release-namespace: kafkaplaypen
+  labels:
+    app.kubernetes.io/instance: kafka-local
+    app.kubernetes.io/managed-by: Helm
+    app.kubernetes.io/name: kafka
+    helm.sh/chart: kafka-20.0.0
+  name: kafka-local-scripts
+  namespace: kafkaplaypen
+---
+apiVersion: v1
+data:
+  init-certs.sh: '#!/bin/bash'
+  setup.sh: |-
+    #!/bin/bash
 
-      # Execute entrypoint as usual after obtaining ZOO_SERVER_ID
-      # check ZOO_SERVER_ID in persistent volume via myid
-      # if not present, set based on POD hostname
-      if [[ -f "/bitnami/zookeeper/data/myid" ]]; then
-          export ZOO_SERVER_ID="$(cat /bitnami/zookeeper/data/myid)"
-      else
-          HOSTNAME="$(hostname -s)"
-          if [[ $HOSTNAME =~ (.*)-([0-9]+)$ ]]; then
-              ORD=${BASH_REMATCH[2]}
-              export ZOO_SERVER_ID="$((ORD + 1 ))"
-          else
-              echo "Failed to get index from hostname $HOST"
-              exit 1
-          fi
-      fi
-      exec /entrypoint.sh /run.sh
-  kind: ConfigMap
-  metadata:
-    annotations:
-      meta.helm.sh/release-name: kafka-local
-      meta.helm.sh/release-namespace: kafkaplaypen
-    labels:
-      app.kubernetes.io/component: zookeeper
-      app.kubernetes.io/instance: kafka-local
-      app.kubernetes.io/managed-by: Helm
-      app.kubernetes.io/name: zookeeper
-      helm.sh/chart: zookeeper-11.0.0
-    name: kafka-local-zookeeper-scripts
-    namespace: kafkaplaypen
+    # Execute entrypoint as usual after obtaining ZOO_SERVER_ID
+    # check ZOO_SERVER_ID in persistent volume via myid
+    # if not present, set based on POD hostname
+    if [[ -f "/bitnami/zookeeper/data/myid" ]]; then
+        export ZOO_SERVER_ID="$(cat /bitnami/zookeeper/data/myid)"
+    else
+        HOSTNAME="$(hostname -s)"
+        if [[ $HOSTNAME =~ (.*)-([0-9]+)$ ]]; then
+            ORD=${BASH_REMATCH[2]}
+            export ZOO_SERVER_ID="$((ORD + 1 ))"
+        else
+            echo "Failed to get index from hostname $HOST"
+            exit 1
+        fi
+    fi
+    exec /entrypoint.sh /run.sh
+kind: ConfigMap
+metadata:
+  annotations:
+    meta.helm.sh/release-name: kafka-local
+    meta.helm.sh/release-namespace: kafkaplaypen
+  labels:
+    app.kubernetes.io/component: zookeeper
+    app.kubernetes.io/instance: kafka-local
+    app.kubernetes.io/managed-by: Helm
+    app.kubernetes.io/name: zookeeper
+    helm.sh/chart: zookeeper-11.0.0
+  name: kafka-local-zookeeper-scripts
+  namespace: kafkaplaypen
 ---
 apiVersion: apps/v1
 kind: StatefulSet
